Fix Test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -42,7 +42,15 @@ jobs:
         run: |
           minikube image load my-python-app:latest
           kubectl apply -f deployment-definition.yaml
-          kubectl apply -f service-defintion.yaml
+          kubectl apply -f service-definition.yaml
+      - name: Ensure deployment is rolled out
+        run: |
+          kubectl rollout status deployment/helloworld
+          if [ $? -ne 0 ]; then
+            echo "Deployment failed to roll out!"
+            exit 1
+          fi
+
   test:
     runs-on: ubuntu-latest
     needs: deploy
@@ -57,6 +65,10 @@ jobs:
         run: |
           minikube status || minikube start
           kubectl config use-context minikube
+          
+      - name: Wait for deployment to be ready
+        run: |
+          kubectl wait --for=condition=available --timeout=60s deployment/helloworld
 
       - name: Verify deployment, service and pods are running
         run: |
